[package]
name = "cubikan-chain-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
cubikan-core = { path = "../cubikan-core" }
parity-scale-codec.workspace = true
serde_json.workspace = true
sha2.workspace = true
subxt.workspace = true
subxt-signer.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
