
//! Autogenerated weights for `pallet_cubikan`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-08-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `cubikan-t1106`, CPU: `AMD Ryzen 9 5900X 12-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// chain/artifacts/benchmarks/cubikan-runtime-v1.runtime-benchmarks.compact.compressed.wasm
// --genesis-builder
// runtime
// --genesis-builder-preset
// development
// --pallets
// pallet_cubikan
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --min-duration
// 0
// --wasm-execution
// compiled
// --output-analysis
// max
// --output-pov-analysis
// max
// --default-pov-mode
// measured
// --hostname-override
// cubikan-t1106
// --json-file
// chain/artifacts/benchmarks/cubikan-pallet-v1.json
// --output
// chain/runtime/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_cubikan`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_cubikan::WeightInfo for WeightInfo<T> {
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::IntentUnits` (r:1 w:1)
	/// Proof: `Cubikan::IntentUnits` (`max_values`: None, `max_size`: Some(218637), added: 221112, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn create_unit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `666`
		//  Estimated: `4131`
		// Minimum execution time: 2_257_147_000 picoseconds.
		Weight::from_parts(2_320_546_000, 0)
			.saturating_add(Weight::from_parts(0, 4131))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::IntentUnits` (r:1 w:1)
	/// Proof: `Cubikan::IntentUnits` (`max_values`: None, `max_size`: Some(218637), added: 221112, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn transition_unit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218804`
		//  Estimated: `222269`
		// Minimum execution time: 7_739_370_000 picoseconds.
		Weight::from_parts(8_015_009_000, 0)
			.saturating_add(Weight::from_parts(0, 222269))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::IntentUnits` (r:1 w:1)
	/// Proof: `Cubikan::IntentUnits` (`max_values`: None, `max_size`: Some(218637), added: 221112, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn complete_unit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218804`
		//  Estimated: `222269`
		// Minimum execution time: 7_735_210_000 picoseconds.
		Weight::from_parts(7_877_790_000, 0)
			.saturating_add(Weight::from_parts(0, 222269))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:0 w:1)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// The range of component `a` is `[0, 16]`.
	fn replace_authorized_submitters(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_340_000 picoseconds.
		Weight::from_parts(4_833_954, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 1_248
			.saturating_add(Weight::from_parts(32_967, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::RelationshipDefinitions` (r:1 w:1)
	/// Proof: `Cubikan::RelationshipDefinitions` (`max_values`: None, `max_size`: Some(685), added: 3160, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn create_relationship_definition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `666`
		//  Estimated: `4131`
		// Minimum execution time: 19_050_000 picoseconds.
		Weight::from_parts(19_690_000, 0)
			.saturating_add(Weight::from_parts(0, 4131))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::RelationshipDefinitions` (r:1 w:0)
	/// Proof: `Cubikan::RelationshipDefinitions` (`max_values`: None, `max_size`: Some(685), added: 3160, mode: `Measured`)
	/// Storage: `Cubikan::IntentUnits` (r:2 w:0)
	/// Proof: `Cubikan::IntentUnits` (`max_values`: None, `max_size`: Some(218637), added: 221112, mode: `Measured`)
	/// Storage: `Cubikan::RelationshipEdges` (r:1 w:1)
	/// Proof: `Cubikan::RelationshipEdges` (`max_values`: None, `max_size`: Some(13660), added: 16135, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn create_relationship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453246`
		//  Estimated: `459186`
		// Minimum execution time: 17_322_423_000 picoseconds.
		Weight::from_parts(17_446_362_000, 0)
			.saturating_add(Weight::from_parts(0, 459186))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::RelationshipDefinitions` (r:1 w:0)
	/// Proof: `Cubikan::RelationshipDefinitions` (`max_values`: None, `max_size`: Some(685), added: 3160, mode: `Measured`)
	/// Storage: `Cubikan::IntentUnits` (r:2 w:0)
	/// Proof: `Cubikan::IntentUnits` (`max_values`: None, `max_size`: Some(218637), added: 221112, mode: `Measured`)
	/// Storage: `Cubikan::RelationshipEdges` (r:1 w:1)
	/// Proof: `Cubikan::RelationshipEdges` (`max_values`: None, `max_size`: Some(13660), added: 16135, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn delete_relationship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `453352`
		//  Estimated: `459292`
		// Minimum execution time: 15_810_339_000 picoseconds.
		Weight::from_parts(15_939_698_000, 0)
			.saturating_add(Weight::from_parts(0, 459292))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::IntentUnits` (r:1 w:0)
	/// Proof: `Cubikan::IntentUnits` (`max_values`: None, `max_size`: Some(218637), added: 221112, mode: `Measured`)
	/// Storage: `Cubikan::ActiveAssociations` (r:1 w:1)
	/// Proof: `Cubikan::ActiveAssociations` (`max_values`: None, `max_size`: Some(77730), added: 80205, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn record_association() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `296481`
		//  Estimated: `299946`
		// Minimum execution time: 8_353_034_000 picoseconds.
		Weight::from_parts(8_455_563_000, 0)
			.saturating_add(Weight::from_parts(0, 299946))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Cubikan::AuthorizedSubmitters` (r:1 w:0)
	/// Proof: `Cubikan::AuthorizedSubmitters` (`max_values`: Some(1), `max_size`: Some(513), added: 1008, mode: `Measured`)
	/// Storage: `Cubikan::IntentUnits` (r:1 w:0)
	/// Proof: `Cubikan::IntentUnits` (`max_values`: None, `max_size`: Some(218637), added: 221112, mode: `Measured`)
	/// Storage: `Cubikan::ActiveAssociations` (r:1 w:1)
	/// Proof: `Cubikan::ActiveAssociations` (`max_values`: None, `max_size`: Some(77730), added: 80205, mode: `Measured`)
	/// Storage: `Cubikan::GlobalSequence` (r:1 w:1)
	/// Proof: `Cubikan::GlobalSequence` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `Measured`)
	/// Storage: `Cubikan::DeploymentAnchor` (r:1 w:0)
	/// Proof: `Cubikan::DeploymentAnchor` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `Measured`)
	/// Storage: `Cubikan::EventSchemaVersion` (r:1 w:0)
	/// Proof: `Cubikan::EventSchemaVersion` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `Measured`)
	fn revoke_association() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `297088`
		//  Estimated: `300553`
		// Minimum execution time: 8_459_842_000 picoseconds.
		Weight::from_parts(8_828_001_000, 0)
			.saturating_add(Weight::from_parts(0, 300553))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
